# -*- coding: utf-8 -*-
"""Day1_Introduction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZT75VDy7YJB2II_C_4C6C4zezCPqOaIe
"""

# Day1_Introduction
print(3 + 2)   # addition(+)
print(3 - 2)   # subtraction(-)
print(3 * 2)   # multiplication(*)
print(3 / 2)   # division(/)
print(3 ** 2)  # exponential(**)
print(10 % 4)   # modulus(%) That means remainder of division
print(3 // 2)  # Floor division operator(//)

# Checking data types

print(type(10))                  # Integer
print(type(3.14))                # Float
print(type(1 + 3j))              # Complex
print(type('Jahid'))             # String
print(type([1, 2, 3]))           # List
print(type({'name':'Jahid'}))    # Dictionary
print(type({9.8, 3.14, 2.7}))    # Set
print(type((9.8, 3.14, 2.7)))    # Tuple
print(type(3 == 3))              # Bool
print(type(3 >= 3))              # Bool